apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
  namespace: kube-prac
provisioner: kubernetes.io/no-provisioner # put in different arguments here ie aws ebs, azurefile etc. 
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - debug
volumeBindingMode: WaitForFirstConsumer
