apiVersion: v1
kind: Pod
metadata: 
  name: pod-node
  namespace: cka-prac
spec:
  containers:
  - name: nginx
    image: nginx

  nodeSelector: 
    size: Large # this is the node selector value key's label that we set. 