apiVersion: v1
kind: Pod
metadata:
  name: node-aff-pod
  namespace: cka-prac
spec:
  containers:
    - name: nginx
      image: nginx
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoreDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: size 
            operator: In   # or Not in, exists etc. 
            value: 
            - Large