apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: cka-prac
  labels:
    name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
      - containerPort: 8080
  nodeName: docker-desktop #my node we want to schedule on 