apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rep
  namespace: cka-prac
  labels:
    app: myapp
    type: front-end
spec: 
  template:   # pod template
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
      - name: nginx-container
        image: nginx
  replicas: 2
  selector: # what pods fall under it and also ones that aren't made by the replicaset
    matchLabels:
      type: front-end
