apiVersion: v1 
kind: Pod
metadata:
  name: nginx-taint
spec: 
  containers:
  - name: nginx-container
    image: nginx
  tolerations:
  - key: "key"
    operator: "Equal" 
    value: "blue"
    effect: "NoSchedule"
