---
apiVersion: v1
kind: Namespace 
metadata:
  name: ocr
---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: ocr_deploy 
  namespace: ocr 
spec: 
  replicas: 3 
  selector:
    matchLabels:
      app: ocr_app 
  template:
    metadata:
      labels: 
        app: ocr_app 
    spec:
      containers:
      - name: ocr-pod
        image: mcr.microsoft.com/azure-cognitive-services/vision/read:3.2-preview.1
        ports:
        - containerPort: 5000 
        env:
        - name: EULA
          valueFrom:
            configMapKeyRef:
              key: EULA
              name: ocr_config 
        - name: billing
          valueFrom:
            configMapKeyRef:
              key: billing
              name: ocr_config 
        - name: apikey 
          valueFrom: 
            configMapKeyRef:
              key: apikey
              name: ocr_config
      imagePullSecrets:
      - name: secret_info 
---
apiVersion: v1
kind: Service 
metadata: 
  name: ocr_service 
  namespace: ocr 
  spec: 
    type: LoadBalancer
    ports:
      - port: 5000 
      selector: 
        app: ocr_app 
        targetPort: 9376 
