apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: plumber-deploy
  namespace: plumber_retrain
  labels:
    app: r-retrain
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: r-retrain
  template:
    metadata:
      labels:
        app: r-retrain
    spec:
      containers:
      - name: r-model
        image: rimage:latest
        ports: 
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: r-svc 
  namespace: pluber_retrain
spec: 
  selector:
    app: r-retrain
  ports: 
    - protocol: TCP
      port: 80
      targetPort: 80
