apiVersion: v1
kind: Namespace
metadata: 
  name: plumber_retrain
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plumber_deploy
  namespace: plumber_retrain
  labels:
    app: plumber
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: plumber_retrain
  template:
    metadata:
      labels:
        app: plumber_retrain
    spec:
      containers:
      - name: plumb 
        image: plumber-image
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: plumb-svc
  namespace: plumber_retrain
spec:
  selector:
    app: plumber_retrain
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: plumber-ingress
  namespace: plumber_retrain
spec:
  rules:
  - http:
    paths:
    - path: /health
      backend:
        serviceName: plumb-svc
        servicePort: 8000
    - path: /parity
      backend:
        serviceName: plumb-svc
        servicePort: 8000
    - path: /wait
      backend: 
        serviceName: plumb-svc
        servicePort: 8000
    - path: /fail
      backend: 
        serviceName: plumb-svc
        servicePort: 8000
    - path: /quit
      backend:
        serviceName: plumb-svc
        servicePort: 8000
