apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: jacob
spec: 
  groups:
  - system:authenticated
  usages:
  - digital signature
  - key encipherment
  - server auth 
  request:
    # comes from bas64 transforming the .csr file
