apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod 
spec:
  containers:
  - name: nginx 
    image: private-registry.io/apps/interal-app
  imagePullSecrets:
  - name: regcred # name of image secret I created earlier 
