apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-pool
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:   # can change this value to make it nfs etc. 
    path: /tmp/data
