apiVersion: v1
kind: Pod
metadata: 
  name: event-sim
  namespace: cka-prac
spec:
  containers:
  - name: event-simulator
    image: kodekloud/event-simulator
  - name: image-processor
    image: nginx
