apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp
  labels:
    name: simple-webapp
spec: 
  containers:
  - name: simple-webapp
    image: nginx
    ports:
      - containerPort: 8080
    envFrom:
      - configMapRef:
          name: my-config
