apiVersion: v1
kind: Pod
metadata:
  name: simple-web-secret
  namespace: cka-prac
spec:
  containers:
  - name: simple-web-secret
    image: nginx
    ports:
      - containerPort: 8080
    envFrom:
    - secretRef:
        name: app-secret