apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello 
      tier: backend
      track: stable 
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hello
        tier: backend 
        track: stable
    spec:
      containers:
      - image: gcr.io/google-samples/hello-go-gke:1.0
        name: hello-go-gke
        ports:
        - name: http
          containerPort: 80
status: {}
