
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mem-demo
  name: mem-demo-2
  namespace: mem
spec:
  containers:
  - image: polinux/stress
    name: mem-demo-2-ctr
    resources:
      limits:
        memory: 100Mi
      requests:
        memory: 50Mi
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytest", "250M", "--vm-hang", "1"]
  dnsPolicy: ClusterFirst
  restartPolicy: Always
