
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mem-demo
  name: mem-demo
  namespace: mem
spec:
  containers:
  - image: polinux/stress
    name: mem-demo
    resources:
      limits:
        memory: 200Mi
      requests:
        memory: 100Mi
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytest", "150M", "--vm-hang", "1"]
  dnsPolicy: ClusterFirst
  restartPolicy: Always
