apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-prac
  namespace: kube-prac
  labels: 
    app: nginx-prac
spec: # the desired state of the resouce. status is the observed state of hte object ie recorded sate the cluster provides to the user
  replicas: 3
  selector: 
    matchLabels:
      app: nginx
  template: 
    metadata:
      labels:
        app: nginx
    spec: 
      containers:
      - name: nginx-prac
        image: nginx
        ports:
        - containerPort: 80
