# statefulset pods have a unique identity comprised of ordinal, stable network identity and stable storage. Identity sticks to pood regardless of which node its rescheduled on. 

apiVersion: v1
kind: Service
metadata: 
  name: nginx
  labels: 
    app: nginx
spec:
  ports:
  - port: 80 
    name: web
  clusterIP: None
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: web
spec:
  selector:
    matchLabels:
      app: nginx # has to match w/ .spec.template.metadata.labels
    serviceName: "nginx"
    replicas: 4
    template:
      metadata:
        labels:
          app: nginx # has to match w/ .spec.selector.matchLabels
      spec:
        terminationGracePeriodSeconds: 10 
        containers:
        - name: nginx
          image: k8s.gcr.io/nginx-slim:0.8
          ports:
          - containerPort: 80
            name: web
          volumeMounts: 
          - name: www
            mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata: 
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassNaem: "my-storage-class"
      resources:
        requests:
          storage: 1Gi
