apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-read 
  namespace: cka-prac
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"] 

# creates pod-reader role, which has access only to read the pods in the cka-ns namespace- then can bind users w/ rolebinding 
