apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: cka-prac
  labels:
    run: web-service
spec:
  type: NodePort
  ports: 
  - port: 80
    protocol: TCP
  selector:
    app: nginx
